import escapeHtml from "escape-html";
import { parseGithubRepo } from "../../lib/validation";

// ---------------------------------------------------------------------------
// Shared contributor-page generation logic.
// Outputs two files published into the staging frontend repo
// (HNG-ZEDU-EGRET/zedu-fe -> CONTRIBUTORS_REPO_DIR, currently
//  src/app/(homepage)/contributors/egrets/):
//   index.ts  - generated data: contributors + their repo link
//   page.tsx  - App Router page styled like the main website
//               (HeroSection / ArticleCard / Button.tsx, primary-500)
//
// IMPORTS in page.tsx are limited to `next` (Metadata) and `./index` —
// everything else (avatar, arrow, cards) is inlined so we never have to
// import repo components or add dependencies.
//
// IMPORTANT: nothing time-dependent may appear in the generated output.
// A timestamp would make every nightly run produce a diff, which would
// trigger a redundant Coolify deployment.
// ---------------------------------------------------------------------------

export const GENERATED_BANNER =
  "// AUTO-GENERATED by zedu-egret-store - do not edit by hand.\n" +
  "// Regenerated on every verified Stage 1 submission (GitHub Action).";

/** One contributor row as published to index.ts. */
export type ContributorEntry = { name: string; repo: string };

/** Collapse whitespace + strip control characters so the generated TS is safe. */
export function cleanName(raw: unknown): string {
  return String(raw ?? "")
    .replace(/[\u0000-\u001F\u007F]/g, "")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 120);
}

/**
 * Proper-case a person name: capitalise the FIRST letter of every word,
 * but only when it is currently lowercase, so intentional inner capitals
 * survive: "john doe" -> "John Doe", "AbdulJaleel AbdulSamad" stays as-is.
 */
export function properCase(name: string): string {
  return name.replace(/\b[a-z]/g, (ch) => ch.toUpperCase());
}

/**
 * Normalise a submitted task repo into a canonical URL.
 * Accepts full URLs and `owner/repo` short forms (both are accepted by the
 * checkout API via parseGithubRepo); anything unparseable -> "" (the member
 * box then renders without a link).
 */
export function normalizeRepoUrl(raw: unknown): string {
  const parsed = parseGithubRepo(String(raw ?? ""));
  if (!parsed) return "";
  return `https://github.com/${parsed.owner}/${parsed.repo}`;
}

/** Escape a string for use inside a double-quoted TS literal. */
export function tsString(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

/**
 * Encode a repo directory path for the GitHub Contents API.
 * Each segment is encoded individually so parentheses survive:
 *   src/app/(homepage)/contributors/egrets -> src/app/%28homepage%29/contributors/egrets
 */
export function encodeRepoPath(path: string): string {
  return path
    .split("/")
    .filter((seg) => seg.length > 0)
    .map((seg) =>
      encodeURIComponent(seg)
        // encodeURIComponent leaves RFC 3986 sub-delims alone; escape the
        // parentheses used by Next.js route groups so no proxy/shell can
        // mis-parse the path (e.g. "(homepage)" -> "%28homepage%29").
        .replace(/\(/g, "%28")
        .replace(/\)/g, "%29")
    )
    .join("/");
}

export function joinRepoPath(dir: string, file: string): string {
  return `${dir.replace(/\/+$/, "")}/${file.replace(/^\/+/, "")}`;
}

/** index.ts - the generated contributor data. */
export function renderIndexTs(entries: ContributorEntry[]): string {
  const rows = entries
    .map((e) => `  { name: ${tsString(e.name)}, repo: ${tsString(e.repo)} },`)
    .join("\n");
  return `${GENERATED_BANNER}

export type Contributor = {
  name: string;
  repo: string;
};

export const contributors: Contributor[] = [
${rows}
];

export const contributorCount = contributors.length;

export default contributors;
`;
}
/**
 * page.tsx - App Router page rendering the contributor list.
 * Styled after the main website:
 *  - HeroSection: section wrapper, h1 with primary-500 accent, metrics grid
 *  - ArticleCard: rounded-2xl bg-white drop-shadow-md card pattern
 *  - Button.tsx:  ArrowBtn rounded-full bg-primary-500 hover:bg-primary-400
 * Member boxes link to the submitted GitHub repo (target=_blank); when no
 * repo could be parsed the box renders without a link.
 */
export function renderPageTsx(): string {
  return `${GENERATED_BANNER}

import type { Metadata } from "next";

import { contributorCount, contributors } from "./index";

export const metadata: Metadata = {
  title: "Zedu Egret Contributors",
  description:
    "Contributors who have actively participated and contributed to Zedu chat during HNG 15 internship in Team Egret.",
  alternates: {
    canonical: "/contributors/egrets",
  },
};

const initialsOf = (name: string) => {
  const parts = name.trim().split(/\s+/);
  const first = parts[0] ? parts[0].charAt(0) : "";
  const last = parts.length > 1 ? parts[parts.length - 1].charAt(0) : "";
  return (first + last).toUpperCase() || "?";
};

const ContributorsPage = () => {
  const repoCount = contributors.filter((entry) => entry.repo !== "").length;
  const stats = [
    { amount: String(contributorCount), text: "Contributors" },
    { amount: String(repoCount), text: "GitHub repos linked" },
    { amount: "HNG 15", text: "Internship" },
  ];

  return (
    <section className="relative isolate flex w-full flex-col items-center gap-4 overflow-hidden px-4 py-10 text-center sm:gap-6 sm:px-8 sm:py-16 lg:gap-8 lg:px-12">
      <h1 className="text-2xl font-semibold leading-tight text-neutral-900 sm:text-4xl md:text-5xl text-center">
        Zedu <span className="text-primary-500">Egret</span> Contributors
      </h1>
      <p className="max-w-[95%] text-xs text-neutral-600 sm:max-w-[90%] sm:text-base md:max-w-[65%] lg:max-w-[45%] lg:text-lg">
        Contributors who have actively participated and contributed to Zedu chat
        during HNG 15 internship in Team Egret.
      </p>

      {/* Stats - mirrors the homepage HeroSection metrics grid */}
      <div className="grid w-full max-w-4xl grid-cols-3 place-items-center gap-1.5 sm:gap-6 md:gap-10">
        {stats.map((stat, i) => (
          <div
            key={i}
            className="flex w-full max-w-[260px] flex-col items-center justify-center gap-1 px-1.5 py-1 sm:px-4 sm:py-3"
          >
            <p className="text-lg font-semibold text-neutral-900 sm:text-3xl">
              {stat.amount}
            </p>
            <p className="text-[10px] leading-tight text-neutral-500 sm:text-sm">
              {stat.text}
            </p>
          </div>
        ))}
      </div>

      {contributorCount === 0 ? (
        <div className="mt-4 w-full max-w-4xl rounded-2xl bg-primary-50 px-6 py-10 text-center">
          <p className="text-sm text-neutral-600">
            No contributors yet. Complete Stage 1 to be the first on this list.
          </p>
        </div>
      ) : (
        <div className="mt-4 grid w-full max-w-7xl grid-cols-1 gap-4 text-left sm:grid-cols-2 lg:grid-cols-3">
          {contributors.map((entry, i) => {
            const base =
              "group flex h-full w-full flex-col gap-3 rounded-2xl bg-white px-5 py-5 drop-shadow-md transition duration-200 hover:-translate-y-0.5";
            const box = (
              <>
                <span className="flex h-11 w-11 items-center justify-center rounded-full bg-primary-50 text-sm font-bold text-primary-500">
                  {initialsOf(entry.name)}
                </span>
                <span className="block truncate text-base font-semibold text-neutral-900">
                  {entry.name}
                </span>
                <span className="block text-xs text-neutral-500">
                  {entry.repo ? "GitHub repository" : "Team Egret contributor"}
                </span>
              </>
            );
            return entry.repo ? (
              <a
                key={i}
                href={entry.repo}
                target="_blank"
                rel="noreferrer"
                className={base + " focus:outline-none focus-visible:ring-2 focus-visible:ring-primary-500"}
              >
                {box}
              </a>
            ) : (
              <div key={i} className={base}>
                {box}
              </div>
            );
          })}
        </div>
      )}

      {/* CTA - ArrowBtn from ui/Button.tsx, inlined (no component import) */}
      <a
        href="/"
        className="group mt-6 inline-flex items-center gap-3 rounded-full bg-primary-500 px-6 py-3 font-medium text-white transition-colors duration-200 hover:bg-primary-400"
      >
        Explore Zedu
        <span className="transition-transform duration-300 ease-out group-hover:translate-x-1">
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" aria-hidden="true">
            <path d="M5 12h14M12 5l7 7-7 7" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
        </span>
      </a>
    </section>
  );
};

export default ContributorsPage;
`;
}

/** Standalone HTML preview used locally and by the legacy build script. */
export function renderHtmlPreview(entries: ContributorEntry[]): string {
  const items = entries
    .map((e) => `      <li>${escapeHtml(e.name)}</li>`)
    .join("\n");
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Zedu Egret Contributors</title>
<style>body{font-family:system-ui,sans-serif;margin:0;background:#f7f7f8;color:#111}.wrap{max-width:960px;margin:0 auto;padding:24px}ul{columns:2;gap:24px;list-style:disc;padding-left:20px}li{margin:4px 0}</style>
</head><body><div class="wrap">
<h1>Zedu Egret Contributors (${entries.length})</h1>
<ul>
${items}
</ul>
</div></body></html>`;
}

/** Files published to the staging repo, keyed by filename. */
export function buildArtifacts(entries: ContributorEntry[]): Record<string, string> {
  return {
    "index.ts": renderIndexTs(entries),
    "page.tsx": renderPageTsx(),
  };
}