import escapeHtml from "escape-html";

// ---------------------------------------------------------------------------
// Shared contributor-page generation logic.
// Outputs two files that are published into the staging frontend repo
// (HNG-ZEDU-EGRET/zedu-fe -> src/app/(homepage)/contributors/):
//   index.ts  - the generated data
//   page.tsx  - the App Router page that renders it
//
// IMPORTANT: nothing time-dependent may appear in the generated output.
// A timestamp would make every nightly run produce a diff, which would
// trigger a redundant Coolify deployment.
// ---------------------------------------------------------------------------

export const GENERATED_BANNER =
  "// AUTO-GENERATED by zedu-egret-store — do not edit by hand.\n" +
  "// Regenerated on every verified Stage 1 submission (GitHub Action).";

/** Collapse whitespace + strip control characters so the generated TS is safe. */
export function cleanName(raw: unknown): string {
  return String(raw ?? "")
    .replace(/[\u0000-\u001F\u007F]/g, "")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 120);
}

/** Escape a string for use inside a double-quoted TS literal. */
export function tsString(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

/**
 * Encode a repo directory path for the GitHub Contents API.
 * Each segment is encoded individually so parentheses survive:
 *   src/app/(homepage)/contributors -> src/app/%28homepage%29/contributors
 */
export function encodeRepoPath(path: string): string {
  return path
    .split("/")
    .filter((seg) => seg.length > 0)
    .map((seg) =>
      encodeURIComponent(seg)
        // encodeURIComponent leaves RFC 3986 sub-delims alone; escape the
        // parentheses used by Next.js route groups so no proxy/shell can
        // mis-parse the path (e.g. "(homepage)" -> "%28homepage%29").
        .replace(/\(/g, "%28")
        .replace(/\)/g, "%29")
    )
    .join("/");
}

export function joinRepoPath(dir: string, file: string): string {
  return `${dir.replace(/\/+$/, "")}/${file.replace(/^\/+/, "")}`;
}

/** index.ts — the generated contributor data. */
export function renderIndexTs(names: string[]): string {
  const rows = names.map((n) => `  { name: ${tsString(n)} },`).join("\n");
  return `${GENERATED_BANNER}

export type Contributor = {
  name: string;
};

export const contributors: Contributor[] = [
${rows}
];

export const contributorCount = contributors.length;

export default contributors;
`;
}

/**
 * page.tsx — App Router page that renders the contributor list.
 * Matches the zedu-fe conventions: tailwind classes only, no new
 * dependencies (keeps their pnpm lockfile untouched).
 */
export function renderPageTsx(): string {
  return `${GENERATED_BANNER}

import type { Metadata } from "next";

import { contributorCount, contributors } from "./index";

export const metadata: Metadata = {
  title: "Zedu Egret Contributors",
  description:
    "Contributors who have completed Stage 1 verification in the Zedu Egret internship.",
  alternates: {
    canonical: "/contributors",
  },
};

const ContributorsPage = () => {
  return (
    <section className="mt-12">
      <div className="mx-auto w-full max-w-5xl px-4 pb-16 sm:px-6">
        <p className="text-xs font-semibold uppercase tracking-widest text-emerald-700">
          Zedu Egret
        </p>
        <h1 className="mt-2 text-3xl font-bold tracking-tight text-gray-900">
          Contributors
        </h1>
        <p className="mt-2 text-sm text-gray-600">
          Everyone who has completed Stage 1 verification.
          {contributorCount > 0
            ? \` \${contributorCount} contributor\${contributorCount === 1 ? "" : "s"} so far.\`
            : " No contributors yet."}
        </p>

        {contributorCount === 0 ? (
          <p className="mt-8 rounded-lg border border-gray-200 bg-gray-50 px-4 py-3 text-sm text-gray-600">
            No contributors yet. Complete Stage 1 to be the first on this list.
          </p>
        ) : (
          <ol className="mt-8 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">
            {contributors.map((contributor, index) => (
              <li
                key={\`\${contributor.name}-\${index}\`}
                className="flex items-center gap-3 rounded-xl border border-gray-200 bg-white px-4 py-3 shadow-sm"
              >
                <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-emerald-50 text-xs font-bold text-emerald-800">
                  {index + 1}
                </span>
                <span className="truncate text-sm font-semibold text-gray-900">
                  {contributor.name}
                </span>
              </li>
            ))}
          </ol>
        )}
      </div>
    </section>
  );
};

export default ContributorsPage;
`;
}

/** Standalone HTML preview used locally and by the legacy build script. */
export function renderHtmlPreview(names: string[]): string {
  const items = names
    .map((n) => `      <li>${escapeHtml(n)}</li>`)
    .join("\n");
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Zedu Egret Contributors</title>
<style>body{font-family:system-ui,sans-serif;margin:0;background:#f7f7f8;color:#111}.wrap{max-width:960px;margin:0 auto;padding:24px}ul{columns:2;gap:24px;list-style:disc;padding-left:20px}li{margin:4px 0}</style>
</head><body><div class="wrap">
<h1>Zedu Egret Contributors (${names.length})</h1>
<ul>
${items}
</ul>
</div></body></html>`;
}

/** Files published to the staging repo, keyed by filename. */
export function buildArtifacts(names: string[]): Record<string, string> {
  return {
    "index.ts": renderIndexTs(names),
    "page.tsx": renderPageTsx(),
  };
}